-- AlterTable
ALTER TABLE "Famille" ADD COLUMN "cmgCotisations" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Famille" ADD COLUMN "cmgRemuneration" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Famille" ADD COLUMN "abattementCharges" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Famille" ADD COLUMN "aideVille" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Famille" ADD COLUMN "creditImpot" DOUBLE PRECISION NOT NULL DEFAULT 0;
